#╔═════════════════════════╗╔════════════════════════════════════╗╔═════════════════════════╗
#║   Наш телеграм канал    ║║      Наше сообщество вконтакте     ║║  Наш дискорд сервер     ║
#║   t.me/spacestudiomc    ║║       vk.com/spacestudiomine       ║║   dsc.gg/spacestudiomc  ║
#╚═════════════════════════╝╚════════════════════════════════════╝╚═════════════════════════╝
#╔═════════════════════════════════════════════════════════════════════════════════════════════╗
#║  ███████╗██████╗  █████╗  ██████╗███████╗    ███████╗████████╗██╗   ██╗██████╗ ██╗ ██████╗  ║
#║  ██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝    ██╔════╝╚══██╔══╝██║   ██║██╔══██╗██║██╔═══██╗ ║
#║  ███████╗██████╔╝███████║██║     █████╗      ███████╗   ██║   ██║   ██║██║  ██║██║██║   ██║ ║
#║  ╚════██║██╔═══╝ ██╔══██║██║     ██╔══╝      ╚════██║   ██║   ██║   ██║██║  ██║██║██║   ██║ ║
#║  ███████║██║     ██║  ██║╚██████╗███████╗    ███████║   ██║   ╚██████╔╝██████╔╝██║╚██████╔╝ ║
#║  ╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝╚══════╝    ╚══════╝   ╚═╝    ╚═════╝ ╚═════╝ ╚═╝ ╚═════╝  ║
#╚═════════════════════════════════════════════════════════════════════════════════════════════╝
#
#                               ╔════════════════════════════════════╗
#                               ║         Кодер - m0onmag            ║
#                               ║         t.me/m0onmag               ║
#                               ╚════════════════════════════════════╝
KickPrefix: '&c&l &7»'
KickNotify: '&b%player% &fбыл кикнут по причине: &cне скачал ресурспак'
KickMessageLines:
  - "&cТы отклонил ресурспак!"
  - "&7Он обязателен для игры."
  - "&eЗайди снова и прими его."
reload: '&aКонфигурация перезагружена!'
nopermission: '&cУ вас недостаточно полномочий!'
usage: '&fИспользование: &b/ssrp reload'