#╔═════════════════════════╗╔════════════════════════════════════╗╔═════════════════════════╗
#║     Кодер - MoonMag     ║║      Студия разработки плагинов    ║║  Помощь - stolinxlive   ║
#║   t.me/@MoonMagOffical  ║║         vk.com/spacestudiomine     ║║    t.me/@stolinxlive    ║
#╚═════════════════════════╝╚════════════════════════════════════╝╚═════════════════════════╝
#╔══════════════════════════════════════════════════════════════════════════════════════════╗
#║░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░║
#║░░██████╗██████╗░░█████╗░░██████╗███████╗░░░░██████╗████████╗██╗░░░██╗██████╗░██╗░█████╗░░║
#║░██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝░░░██╔════╝╚══██╔══╝██║░░░██║██╔══██╗██║██╔══██╗░║
#║░╚█████╗░██████╔╝███████║╚█████╗░█████╗░░░░░╚█████╗░░░░██║░░░██║░░░██║██║░░██║██║██║░░██║░║
#║░░╚═══██░██╔═══╝░██╔══██║░╚═══██╗██╔══╝░░░░░░╚═══██╗░░░██║░░░██║░░░██║██║░░██║██║██║░░██║░║
#║░██████╔╝██║░░░░░██║░░██║██████╔╝███████╗░░░██████╔╝░░░██║░░░╚██████╔╝██████╔╝██║╚█████╔╝░║
#║░╚═════╝░╚═╝░░░░░╚═╝░░╚═╝╚═════╝░╚══════╝░░░╚═════╝░░░░╚═╝░░░░╚═════╝░╚═════╝░╚═╝░╚════╝░░║
#║░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░║
#╚══════════════════════════════════════════════════════════════════════════════════════════╝
#╔═════════════════════════╗╔════════════════════════════════════╗╔═════════════════════════╗
#║        Не забудь        ║║        Наш телеграм канал:         ║║       Наш дискорд       ║
#║    Поставить оценочку)  ║║        t.me/spacestudiomc          ║║    dsc.gg/spacestudiomc ║
#╚═════════════════════════╝╚════════════════════════════════════╝╚═════════════════════════╝
KickPrefix: '&c&l &8&l>'
KickMessage: '&8%player% &7игрок кинут по причине не скачал ресурс пак'
Line-1: '&4Вы должны включить &f"&6Наборы ресурсов&f" &4сервера, чтоб играть на сервере!'
Line-2: '&4Выйдете в меню и в настройках сервера включите &f"&6Наборы ресурсов&f"'
reload: '&x&9&a&9&8&9&7S&x&9&0&8&e&8&dp&x&8&6&8&4&8&3a&x&7&b&7&a&7&9c&x&7&1&7&0&6&fe&x&6&7&6&6&6&5S&x&5&d&5&c&5&ct&x&5&3&5&2&5&2u&x&4&9&4&8&4&8d&x&3&e&3&e&3&ei&x&3&4&3&4&3&4o §7» &aКонфигурация перезагружена!'
nopermission: '&x&9&a&9&8&9&7S&x&9&0&8&e&8&dp&x&8&6&8&4&8&3a&x&7&b&7&a&7&9c&x&7&1&7&0&6&fe&x&6&7&6&6&6&5S&x&5&d&5&c&5&ct&x&5&3&5&2&5&2u&x&4&9&4&8&4&8d&x&3&e&3&e&3&ei&x&3&4&3&4&3&4o §7» &cУ вас недостаточно полномочий!'
usage: '&x&9&a&9&8&9&7S&x&9&0&8&e&8&dp&x&8&6&8&4&8&3a&x&7&b&7&a&7&9c&x&7&1&7&0&6&fe&x&6&7&6&6&6&5S&x&5&d&5&c&5&ct&x&5&3&5&2&5&2u&x&4&9&4&8&4&8d&x&3&e&3&e&3&ei&x&3&4&3&4&3&4o §7» &fИспользование: &6/spaceresourcepack reload'