#╔═════════════════════════╗╔════════════════════════════════════╗╔═════════════════════════╗
#║   Наш телеграм канал    ║║      Наше сообщество вконтакте     ║║  Наш дискорд сервер     ║
#║   t.me/spacestudiomc    ║║       vk.com/spacestudiomine       ║║   dsc.gg/spacestudiomc  ║
#╚═════════════════════════╝╚════════════════════════════════════╝╚═════════════════════════╝
#╔═════════════════════════════════════════════════════════════════════════════════════════════╗
#║  ███████╗██████╗  █████╗  ██████╗███████╗    ███████╗████████╗██╗   ██╗██████╗ ██╗ ██████╗  ║
#║  ██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝    ██╔════╝╚══██╔══╝██║   ██║██╔══██╗██║██╔═══██╗ ║
#║  ███████╗██████╔╝███████║██║     █████╗      ███████╗   ██║   ██║   ██║██║  ██║██║██║   ██║ ║
#║  ╚════██║██╔═══╝ ██╔══██║██║     ██╔══╝      ╚════██║   ██║   ██║   ██║██║  ██║██║██║   ██║ ║
#║  ███████║██║     ██║  ██║╚██████╗███████╗    ███████║   ██║   ╚██████╔╝██████╔╝██║╚██████╔╝ ║
#║  ╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝╚══════╝    ╚══════╝   ╚═╝    ╚═════╝ ╚═════╝ ╚═╝ ╚═════╝  ║
#╚═════════════════════════════════════════════════════════════════════════════════════════════╝
#
#                               ╔════════════════════════════════════╗
#                               ║         Кодер - m0onmag            ║
#                               ║         t.me/m0onmag               ║
#                               ╚════════════════════════════════════╝
name: SpaceResourcePack
main: ru.moonmag.SpaceResourcePack
version: 1.6
api-version: 1.16
author: [ m0onmag ]
website: https://spaceforum.net
commands:
  spaceresourcepack:
    permission: ssrp.admin
    aliases: ssrp
permissions:
  ssrp.admin:
    default: op
