#╔═════════════════════════╗╔════════════════════════════════════╗╔═════════════════════════╗
#║     Кодер - MoonMag     ║║      Студия разработки плагинов    ║║  Помощь - stolinxlive   ║
#║   t.me/@MoonMagOffical  ║║         vk.com/spacestudiomine     ║║    t.me/@stolinxlive    ║
#╚═════════════════════════╝╚════════════════════════════════════╝╚═════════════════════════╝
#╔══════════════════════════════════════════════════════════════════════════════════════════╗
#║░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░║
#║░░██████╗██████╗░░█████╗░░██████╗███████╗░░░░██████╗████████╗██╗░░░██╗██████╗░██╗░█████╗░░║
#║░██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝░░░██╔════╝╚══██╔══╝██║░░░██║██╔══██╗██║██╔══██╗░║
#║░╚█████╗░██████╔╝███████║╚█████╗░█████╗░░░░░╚█████╗░░░░██║░░░██║░░░██║██║░░██║██║██║░░██║░║
#║░░╚═══██░██╔═══╝░██╔══██║░╚═══██╗██╔══╝░░░░░░╚═══██╗░░░██║░░░██║░░░██║██║░░██║██║██║░░██║░║
#║░██████╔╝██║░░░░░██║░░██║██████╔╝███████╗░░░██████╔╝░░░██║░░░╚██████╔╝██████╔╝██║╚█████╔╝░║
#║░╚═════╝░╚═╝░░░░░╚═╝░░╚═╝╚═════╝░╚══════╝░░░╚═════╝░░░░╚═╝░░░░╚═════╝░╚═════╝░╚═╝░╚════╝░░║
#║░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░║
#╚══════════════════════════════════════════════════════════════════════════════════════════╝
#╔═════════════════════════╗╔════════════════════════════════════╗╔═════════════════════════╗
#║        Не забудь        ║║        Наш телеграм канал:         ║║       Наш дискорд       ║
#║    Поставить оценочку)  ║║        t.me/spacestudiomc          ║║    dsc.gg/spacestudiomc ║
#╚═════════════════════════╝╚════════════════════════════════════╝╚═════════════════════════╝
name: SpaceResourcePack
main: ru.moonmag.SpaceResourcePack
version: 1.5
api-version: 1.16
author: [ MoonMag ]
commands:
  spaceresourcepack:
    permission: ssrp.admin
    aliases: ssrp
permissions:
  ssrp.admin:
    default: op
